2024-01-24 21:13:05,266 (254272/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2024-01-24 21:13:05,266 (254272/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-01-24 21:13:05,276 (254272/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/jc/.local/share/pipx/venvs/pgcli/lib/python3.11/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/home/jc/.local/share/pipx/venvs/pgcli/lib/python3.11/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/jc/.local/share/pipx/venvs/pgcli/lib/python3.11/site-packages/pgcli/pgexecute.py", line 181, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/home/jc/.local/share/pipx/venvs/pgcli/lib/python3.11/site-packages/pgcli/pgexecute.py", line 230, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/jc/.local/share/pipx/venvs/pgcli/lib/python3.11/site-packages/psycopg/connection.py", line 749, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection is bad: No such file or directory\n\tIs the server running locally and accepting connections on that socket?\n'
